#%RAML 1.0
title: githubsyncanypoint
mediaType: application/json

/test:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Hare Krishna"
              }

/ping:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Vishnu is live"
              }              