#%RAML 1.0
title: githubsyncanypoint
mediaType: application/json

/test:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Hare Krishna"
              }
              
/message:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Hi"
              }     
              
/location:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "kanpur"
              }                                                             